# Use the official Node.js image
FROM node:14

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all files from the current directory to the working directory
COPY . .

# Expose a port (e.g., 3000) that your Node.js app will listen on
EXPOSE 3000

# Command to run the Node.js application
CMD ["node", "Index.js"]
